replicaCount: 1

image:
  repository: ghcr.io/cloudraftio/metrics-app
  pullPolicy: IfNotPresent
  tag: "1.1"


service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: metrics.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

  spec:
    rules:
      - host: metrics.local
        http:
          paths:
            - path: /()(counter)
              pathType: Prefix
              backend:
                service:
                  name: metrics-service
                  port:
                    number: 80

env:
  PASSWORD: MYPASSWORD
