apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  labels:
    {{- include "metrics-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{. Values.image.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "metrics-app.selectorLabels" . | nindent 4 }}
